---

- hosts: all
  become: yes
  name: Register all servers
  roles:
    - rhel_register_node

- hosts: masters
  become: yes
  name: Prep masters
  roles:
    - ocp_configure_node
  vars:
    - node_type: master

- hosts: compute
  become: yes
  name: Prep compute nodes
  roles:
    - ocp_configure_node
  vars:
    - node_type: compute
    
- hosts: glusterfs
  become: yes
  name: Prep glusterfs nodes
  roles:
    - ocp_configure_node
  vars:
    - node_type: glusterfs
  
- import_playbook: "../openshift-ansible/playbooks/byo/config.yml"






