---

- hosts: all
  strategy: free
  become: yes
  name: Register all servers
  roles:
    - rhel_register_node

- hosts: masters
  name: customise (skin) console
  roles:
    - ocp_skin_cluster

#  strategy: free
#  name: Install Nagios client
#  roles:
#    - nagios_install_client

#- hosts: all
#  strategy: free
#  name: Register Nagios client with server
#  roles:
#    - nagios_register_client
#  vars:
#    - nagios_client_hostname: "{{ ansible_hostname }}"
#    - nagios_clientip_address: "{{ ansible_all_ipv4_addresses[0] }}"
