---
- name: ocp_configure_node
  src: https://github.com/prometeo-cloud/ocp_configure_node
  
- name: rhel_register_node
  src: https://github.com/prometeo-cloud/rhel_register_node

- name: ocp_create_master_service_account
  src: https://github.com/prometeo-cloud/ocp_create_master_service_account.git

