---
ansible_ssh_user: ec2-user
ansible_become: "yes"
# openshift_deployment_type: openshift-enterprise
openshift_disable_check: disk_availability,docker_image_availability,docker_storage,memory_availability,package_availability,package_version
deployment_type: openshift-enterprise
containerized: "True"
openshift_release: v3.6
openshift_image_tag: v3.6.173.0.49
# openshift_http_proxy: http://example%5C0025492:PASSWORD@10.0.3.106:80
# openshift_https_proxy: http://example%5C0025492:PASSWORD@10.0.3.106:80
# openshift_no_proxy: 'local,localhost,localdomain,example.com'
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'True', 'challenge': 'True', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_file: "{{ inventory_dir }}/../templates/htpasswd"
# openshift_hosted_registry_storage_kind: glusterfs
# openshift_master_cluster_method: native
# openshift_master_cluster_hostname: ocpsitmaster-internal.example.com
# openshift_master_cluster_public_hostname: ocpsitmaster.example.com
# osm_cluster_network_cidr: 10.128.0.0/14
# openshift_portal_net: 172.30.0.0/16
#  Provide local certificate paths which will be deployed to masters
# openshift_master_named_certificates: [{"certfile": "/root/openshift.crt", "keyfile": "/root/openshift.key", "cafile": "/root/ca-chain.pem"}]
# openshift_master_overwrite_named_certificates: "True"
# openshift_hosted_router_certificate: {"certfile": "/root/wildcard.crt", "keyfile": "/root/wildcard.key", 'cafile': '/root/ca-chain.pem' }
#  Install the openshift examples
openshift_install_examples: "True"
# Audit logging
# openshift_master_audit_config: {"basicAuditEnabled": "True"}
# openshift_master_audit_config: {"enabled": "True", "auditFilePath": "/var/log/openpaas-oscp-audit/openpaas-oscp-audit.log", "maximumFileRetentionDays": 14, "maximumFileSizeMegabytes": 500, "maximumRetainedFiles": 5}
openshift_node_kubelet_args: {'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}
openshift_master_default_subdomain: cloudapps.example.com
openshift_router_selector: 'infra=true'
openshift_registry_selector: 'infra=true'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
openshift_hosted_metrics_deploy: "True"
openshift_metrics_install_metrics: "True"
openshift_metrics_start_cluster: "True"
# openshift_metrics_hawkular_hostname: hawkular-metrics.sitapps.example.com
openshift_metrics_cassandra_limits_memory: 1Gi
openshift_metrics_hawkular_limits_memory: 2Gi
openshift_metrics_heapster_limits_memory: 1Gi
# openshift_metrics_image_version: v3.6.173.0.5
openshift_metrics_cassandra_nodeselector: {"infra":"True"}
openshift_metrics_hawkular_nodeselector: {"infra":"True"}
openshift_metrics_heapster_nodeselector: {"infra":"True"}
openshift_metrics_hawkular_agent_nodeselector: {"infra":"True"}
#  Set upgrade restart mode for full system restarts
openshift_rolling_restart_mode: system
openshift_storage_glusterfs_wipe: "True"
openshift_logging_install_logging: "True"
openshift_logging_storage_kind: dynamic
